(* RBX is just ElementContent with DocType *)
RBX = Doctype
    | Tag
    | Expression
    | PlainText
    | Comment ;

(* Tags *)
Tag            = OpenTag
               , [ ElementContent
                 , CloseTag ] ;
OpenTag        = '<'
               , [ Whitespace ]
               , TagName
               , { Whitespace
                 , Attribute }
               , [ Whitespace ]
               , [ '/' ]
               , '>' ;
ElementContent = { Tag
                 | Expression
                 | PlainText
                 | Comment } ;
CloseTag       = '</'
               , [ Whitespace ]
               , TagName
               , [ Whitespace ]
               , '>' ;
TagName        = Alpha
               , { Alpha
                 | Digit
                 | '-'
                 | '_'
                 | '.' } ;
Doctype        = '<!'
               , ( 'DOCTYPE'
                 | 'doctype' )
               , PlainText
               , '>' ;
Comment        = '<!--'
               , { AnyCharacter }
               , '-->' ;
PlainText      = { AnyCharacter - '<' } ;

(* Tag Attributes *)
Attribute           = AttributeAssignment
                    | AttributeName
                    | Expression ;
AttributeAssignment = AttributeName
                    , [ Whitespace ]
                    , '='
                    , [ Whitespace ]
                    , AttrValue ;
AttributeName       = Alpha
                    , { Alpha
                      | Digit
                      | '-'
                      | '_'
                      | ':' } ;
AttrValue           = UnquotedVal
                    | QuotedVal
                    | Expression ;

(* Attribute Value Variants *)
UnquotedVal = { AnyCharacter - ( Whitespace
                               | '"'
                               | "'"
                               | '='
                               | '<'
                               | '>'
                               | '`' ) } ;
QuotedVal   = Quote
            , { AnyCharacter - '"' }
            , Quote ;

(* RBX Specific stuff *)
Expression = '{'
           , PlainText
           , [ Tag ]
           , PlainText
           , '}' ;

(* Foundational things *)
Quote        = "'"
             | '"' ;
Whitespace   = { ''
               | '\t'
               | '\r'
               | '\n' } ;
Alpha        = 'a' - 'z'
             | 'A' - 'Z' ;
Digit        = '0' - '9' ;
AnyCharacter = ? All valid Unicode characters ? ;
